### ISSUE TITLE
Missing .htaccess file

### ISSUE THREAD

**Issue by kennedykenny9** [classiebit/addchat-codeigniter#2]
I downloaded but I could not see the .htaccess file so I could not use this on my codeigniter application.
kindly help

**Comment by classiebit** [comment]
Hi, .htaccess file is needed inside your existing Codeigniter website, .htaccess is not part of addchat-Codeigniter, it's just a plugin. Have a look at the installation video- https://classiebit.com/academy/addchat-codeigniter/getting-started
