### ISSUE TITLE
Interval Server Error after installation

### ISSUE THREAD

**Issue by GirkovArpa** [classiebit/addchat-codeigniter#3]
After installing addchat and adding the appropriate code to the PHP of my homepage as directed, I don't see a chat widget.  I just see the original homepage.  In the console I see this error:

> addchat.min.js:21 POST http://localhost:3000/addchat_api/get_config 500 (Internal Server Error)

Any idea what might be the problem?

**Comment by classiebit** [comment]
Hi, make sure you've added this same base_url in application/config/config.php

**Comment by GirkovArpa** [comment]
```php
$config['base_url'] = 'http://localhost:3000/';
```
Same error, using the command `php -S 127.0.0.1:3000` run via command prompt in the project directory.

Hosting the site with XAMPP instead, I get this error:
> addchat.min.js:21 POST http://localhost/addchat_api/get_config 404 (Not Found)

There is a file:
```
application/controllers/Addchat_api.php
```
But not a corresponding file in the `views` folder.  This file does not exist:
```
application/views/Addchat_api.php
```
Could that be the problem? Shouldn't the addchat installation have created such a file?
